package io.github.tuanmanh28.learn.lesson01.exercises

// Shared types for the exercises — DO NOT edit this file.

sealed interface AdLoadResult {
    data class Loaded(val network: String, val ecpm: Double) : AdLoadResult
    data object NoFill : AdLoadResult
    data class Failed(val code: Int, val message: String) : AdLoadResult
}

interface AdNetwork {
    val name: String
    val priority: Int get() = 0
    fun load(unitId: String): AdLoadResult
}

sealed interface AdEvent {
    data class Impression(val network: String, val revenueMicros: Long) : AdEvent
    data class Click(val network: String) : AdEvent
    data class LoadFailed(val network: String, val code: Int) : AdEvent
    data object Closed : AdEvent
}
